[package]
name = "hasan7990l-hue/youtubedownload"
version = "0.1.0"
description = "Telegram Search Bot with Flask"

[[commands]]
name = "run"
# هنا التعديل: نقوم بتوجيه المنصة لملف bot والمتغير app ليتم تشغيله عبر خادم الويب مباشرة
module = "bot:app" 

[app]
public = true

[[app.routes]]
path = "/*"
backend = "cmd:run"
